name: Readme stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: daniellop1/stats@master
        with:
          WAKATIME_API_KEY: ${{ 082ee238-2d96-4841-b085-87f778cf9587}}
